module.exports = {
  movie: {
    movie_pk: "ID phim bị trùng",
    not_found: "Tên phim không tồn tại",
    missing_title: "Thiếu tên phim",
    missing_slug: "Thiếu slug phim",
    missing_poster: "Thiếu poster ",
    poster_invalid: "Ảnh bìa không đúng định dạng",
    missing_releaseMovie: "Thiếu năm phát hành phim",
    missing_urlTrailer: "Thiếu dường dẫn trailer phim",
    missing_typeMovie: "Thiếu loại phim",
    missing_rating: "Thiếu đánh giá phim",
    missing_poster: "Thiếu poster phim",
    add_success: "Thêm thành công",
    update_success: "Cập nhật thành công",
    rating_constraint: "Đánh giá phim từ 0 đến 10",
  },
  genre: {
    genre_pk: "Tên thể loại phim bị trùng",
    not_found: "Thể loại này không tồn tại",
    missing_title: "Thiếu tên thể loại",
    update_success: "Cập nhật thành công",
    delete_success: "Xóa thành công",
  },
  viewer: {
    not_found: "Tên người dùng không tồn tại",
    username_required: "Yêu cầu cung cấp số điện thoại",
    username_invalid: "Số điện thoại không hợp lệ",
    followed_movie: "Đã follow phim",
    can_not_follow_movie: "Không thể follow phim",
    unfollowed_movie: "Đã unfollow phim",
    can_not_unfollow_movie: "Không thể unfollow phim",
    account_locked: "Tài khoản này đã bị khóa",
  },
  comment: {
    comment_pk: "Thông báo này đã tồn tại",
    viewer_comment_fk: "Người xem này không tồn tại",
  },
  file: {
    not_exist: "Tên file không tồn tại",
  },
  auth: {
    unauthorized: "Cần tài khoản để thực hiện chức năng này",
    token_invalid: "Token không khả dụng",
    forbidden: "Tài khoản không được phép thực hiện chức năng này",
  },
};
